# -*- coding: utf-8 -*-
"""Image_generation_using _openAI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18jhN4vF0WF6BhQQOvVELMOwOyQrJJA1b
"""

pip install openai

import openai
import urllib.request
from PIL import Image
import cv2
from google.colab.patches import cv2_imshow

openai.api_key = "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"

img_response = openai.Image.create(
    prompt = "a boy playing cricket",
    n=1,
    size= "512x512")

img_response

img_response['data'][0]['url']

img_url = img_response['data'][0]['url']
img_url



urllib.request.urlretrieve(img_url, 'image.png')

img = cv2.imread("image.png")
cv2_imshow(img)